version: '3'
services:
    django:
        build: ./scholl-app
        command: sh entrypoint.sh
        env_file: ./scholl-app/.env
        volumes:
        - ./scholl-app:/code
        ports:
        - "8000:8000"
    react:
        stdin_open: true
        image: node
        tty: true
        working_dir: /frontend
        environment:
            - NODE_ENV=development
        command:
            sh entrypoint.sh
        volumes:
        - ./scholl-app/frontend:/frontend
        - /frontend/node_modules
    nginx:
        image: nginx:latest
        ports:
            - 80:8080
        volumes:
            - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./scholl-app/frontend/build:/var/www/frontend # maps frontend build inside nginx
        depends_on:
            - django