# Generated by Django 2.2.4 on 2020-05-30 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangBukti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('nama_barang', models.CharField(blank=True, max_length=255, null=True)),
                ('sp_sita', models.CharField(blank=True, max_length=255, null=True)),
                ('tap_sita', models.CharField(blank=True, max_length=255, null=True)),
                ('tap_status', models.CharField(blank=True, max_length=255, null=True)),
                ('nomor_lab', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_barang', models.CharField(blank=True, choices=[('narkotika', 'narkotika'), ('non narkotika', 'non narkotika')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BerkasLKN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('LKN', models.CharField(max_length=80, unique=True)),
                ('tgl_dibuat', models.DateField(blank=True, null=True)),
                ('penyidik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peyidik_lkn', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Penangkapan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('no_penangkapan', models.CharField(max_length=255, unique=True)),
                ('tanggal_penangkapan', models.DateField(blank=True, null=True)),
                ('masa_berakhir_penangkapan', models.DateField(blank=True, null=True)),
                ('no_lkn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penangkapan', to='organizations.BerkasLKN')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProsesPengadilan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proses', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Tersangka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('nama_tersangka', models.CharField(max_length=255)),
                ('umur', models.SmallIntegerField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media')),
                ('no_penangkapan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penangkapan_tersangka', to='organizations.Penangkapan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusTersangka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status_penahanan', models.CharField(blank=True, choices=[('Di tahan', 'Di tahan'), ('Di Amankan', 'Di Amankan'), ('TAT', 'TAT'), ('Selesai', 'Selesai')], max_length=125, null=True)),
                ('rekam_jejak', models.CharField(blank=True, choices=[('Keluar', 'Keluar'), ('Masuk', 'Masuk')], max_length=125, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('waktu', models.TimeField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tersangka_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statustersangka', to='organizations.Tersangka')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusBarangBukti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('tanggal_status', models.DateField(blank=True, null=True)),
                ('waktu_status', models.TimeField(blank=True, null=True)),
                ('jumlah', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('satuan', models.CharField(choices=[('gram', 'gram'), ('Kg', 'Kg'), ('PCS', 'PCS')], max_length=255)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Keluar', 'Keluar'), ('Masuk', 'Masuk')], max_length=20, null=True)),
                ('approve_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('REJECT', 'REJECT'), ('APPROVE', 'APPROVE')], default='PENDING', max_length=50, null=True)),
                ('moderator_one_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('REJECT', 'REJECT'), ('APPROVE', 'APPROVE')], default='PENDING', max_length=50, null=True)),
                ('moderator_two_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('REJECT', 'REJECT'), ('APPROVE', 'APPROVE')], default='PENDING', max_length=50, null=True)),
                ('moderator_three_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('REJECT', 'REJECT'), ('APPROVE', 'APPROVE')], default='PENDING', max_length=50, null=True)),
                ('barang_bukti_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusbarangbukti', to='organizations.BarangBukti')),
                ('moderator_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator1', to=settings.AUTH_USER_MODEL)),
                ('moderator_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator3', to=settings.AUTH_USER_MODEL)),
                ('moderator_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProsesTersangka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('sp_han', models.CharField(blank=True, max_length=255, null=True)),
                ('sp_han_doc', models.FileField(blank=True, null=True, upload_to='dokumen/sphan')),
                ('tap_han', models.CharField(blank=True, max_length=255, null=True)),
                ('tap_han_doc', models.FileField(blank=True, null=True, upload_to='dokumen/taphan')),
                ('surat_perpanjangan_han', models.CharField(blank=True, max_length=255, null=True)),
                ('surat_perpanjangan_han_doc', models.FileField(blank=True, null=True, upload_to='dokumen/perpanjanghan')),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_proses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proses_pengadilan', to='organizations.ProsesPengadilan')),
                ('proses_tersangka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prosestersangka', to='organizations.Tersangka')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='barangbukti',
            name='milik_tersangka_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barangbuktitersangka', to='organizations.Tersangka'),
        ),
    ]
