# Generated by Django 3.0.4 on 2020-04-08 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200405_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDivision',
            fields=[
                ('basetimestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseTimeStampModel')),
                ('division_name', models.CharField(max_length=255)),
                ('division_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_division', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.basetimestampmodel',),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('basetimestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseTimeStampModel')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division', to='organizations.CompanyDivision')),
                ('company_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_company', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.basetimestampmodel',),
        ),
    ]
