# Generated by Django 2.2.10 on 2020-05-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusbarangbukti',
            name='satuan',
            field=models.CharField(choices=[('gram', 'gram'), ('Kg', 'Kg'), ('PCS', 'PCS')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
