# Generated by Django 3.0.4 on 2020-04-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penangkapan',
            name='jam_penangkapan',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penangkapan',
            name='tanggal_penangkapan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
