# Generated by Django 2.2.10 on 2020-05-31 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangbukti',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='barangbukti',
            name='updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='berkaslkn',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='berkaslkn',
            name='updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='penangkapan',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='penangkapan',
            name='updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prosestersangka',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='prosestersangka',
            name='updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='statusbarangbukti',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='statusbarangbukti',
            name='satuan',
            field=models.CharField(choices=[('gram', 'gram'), ('butir', 'butir'), ('PCS', 'PCS'), ('unit', 'unit')], max_length=255),
        ),
        migrations.AlterField(
            model_name='statusbarangbukti',
            name='updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='statustersangka',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='statustersangka',
            name='updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tersangka',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='tersangka',
            name='updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
