# Generated by Django 3.0.4 on 2020-04-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200411_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusbarangbukti',
            name='tgl_waktu',
        ),
        migrations.RemoveField(
            model_name='statustersangka',
            name='waktu_tanggal',
        ),
        migrations.AddField(
            model_name='statusbarangbukti',
            name='tanggal_status',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statusbarangbukti',
            name='waktu_status',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statustersangka',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statustersangka',
            name='waktu',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
