# Generated by Django 2.2.4 on 2020-05-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200509_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosestersangka',
            name='sp_han',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
