# Generated by Django 3.0.4 on 2020-04-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_prosestersangka_proses_tersangka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkaslkn',
            name='tgl_dibuat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
