# Generated by Django 2.2.4 on 2020-04-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200426_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosestersangka',
            name='proses_tersangka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prosestersangka', to='organizations.Tersangka'),
        ),
    ]
