# Generated by Django 3.0.4 on 2020-04-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200411_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosestersangka',
            name='proses_tersangka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosestersangka', to='organizations.Tersangka'),
        ),
    ]
