# Generated by Django 2.2.10 on 2020-05-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200531_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangbukti',
            name='nomor_lab_doc',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/barangbukti/nomor_lab'),
        ),
        migrations.AddField(
            model_name='barangbukti',
            name='sp_sita_doc',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/barangbukti/sp_sita'),
        ),
        migrations.AddField(
            model_name='barangbukti',
            name='tap_sita_doc',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/barangbukti/tap_sita'),
        ),
        migrations.AddField(
            model_name='barangbukti',
            name='tap_status_doc',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/barangbukti/tap_status'),
        ),
        migrations.AddField(
            model_name='penangkapan',
            name='dokumen_penangkapan',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/penangkapan'),
        ),
        migrations.AddField(
            model_name='penangkapan',
            name='dokumen_sp_jangkap',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/sp_jangkap'),
        ),
        migrations.AddField(
            model_name='penangkapan',
            name='masa_berakhir_sp_jangkap',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penangkapan',
            name='sp_jangkap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='penangkapan',
            name='tanggal_sp_jangkap',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prosestersangka',
            name='tanggal_akhir_proses',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prosestersangka',
            name='tanggal_mulai_proses',
            field=models.DateField(blank=True, null=True),
        ),
    ]
