# Generated by Django 3.0.4 on 2020-04-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20200412_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustersangka',
            name='status_tersangka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statustersangka', to='organizations.Tersangka'),
        ),
    ]
