# Generated by Django 3.0.4 on 2020-04-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20200412_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statustersangka',
            old_name='status_tersangka',
            new_name='tersangka_id',
        ),
    ]
