# Generated by Django 3.0.4 on 2020-04-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20200412_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangbukti',
            old_name='milik_tersangka',
            new_name='milik_tersangka_id',
        ),
    ]
