# Generated by Django 3.0.4 on 2020-04-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20200412_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangbukti',
            name='milik_tersangka_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barangbuktitersangka', to='organizations.Tersangka'),
        ),
        migrations.AlterField(
            model_name='statustersangka',
            name='rekam_jejak',
            field=models.CharField(blank=True, choices=[('Keluar', 'Keluar'), ('Masuk', 'Masuk')], max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='statustersangka',
            name='status_penahanan',
            field=models.CharField(blank=True, choices=[('Di tahan', 'Di tahan'), ('Di Amankan', 'Di Amankan')], max_length=125, null=True),
        ),
    ]
