# Generated by Django 3.0.4 on 2020-04-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20200412_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusbarangbukti',
            old_name='barang_bukti',
            new_name='barang_bukti_id',
        ),
    ]
