# Generated by Django 2.2.10 on 2020-08-16 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notify', '0002_notificationslkn_topic_fcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationslkn',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='notificationslkn',
            name='receiver',
        ),
        migrations.AddField(
            model_name='notificationslkn',
            name='receiver',
            field=models.ManyToManyField(related_name='notifuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
