# Generated by Django 2.2.10 on 2020-08-16 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_auto_20200816_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationslkn',
            name='receiver',
            field=models.ManyToManyField(blank=True, null=True, related_name='notifuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
