# Generated by Django 2.2.10 on 2020-05-02 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetimestampmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 12, 59, 8, 642296)),
        ),
    ]
