# Generated by Django 2.2.10 on 2020-05-02 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200502_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetimestampmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 13, 2, 30, 534988)),
        ),
    ]
