# Generated by Django 2.2.10 on 2020-05-02 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200502_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetimestampmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
